name: MobPlugin
main: de.kniffo80.mobplugin.MobPlugin
version: "1.0"
api: ["1.0.6"]

load: STARTUP
author: kniffo80, matt404, augesrob, PetteriM1, PikyCZ, zzz1999
description: Mob plugin for NukkitX
website: https://github.com/Nukkit-coders/MobPlugin

commands:
 mob:
  description: Mob plugin main command
  aliases: ["mob"]
  usage: /mob
  permission: mobplugin.command

permissions:
 mobplugin.command:
  description: ""
  default: op
