name: MobPlugin
main: nukkitcoders.mobplugin.MobPlugin
version: "1.1"
api: ["1.0.7"]

author: kniffo80, matt404, augesrob, PetteriM1, PikyCZ, zzz1999
description: Entity AI & autospawn plugin for NukkitX servers
website: https://nukkitx.com/resources/mobplugin.3/

commands:
 mob:
  description: Mob plugin main command
  aliases: ["mob"]
  usage: /mob
  permission: mobplugin.command

permissions:
 mobplugin.command:
  description: ""
  default: op
